version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - ocramius
  assignees:
  - ocramius
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: composer/xdebug-handler
    versions:
    - 1.4.6
  - dependency-name: symfony/string
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.6
  - dependency-name: symfony/console
    versions:
    - 5.2.4
  - dependency-name: felixfbecker/language-server-protocol
    versions:
    - 1.5.1
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
